// playground/svelte/src/App.svelte
<script lang="ts">
  import { createTween, createTimeline } from "@thednp/tween/svelte";
  import { Easing } from "@thednp/tween";
  import svelteLogo from "./assets/svelte.svg";
  import viteLogo from "/vite.svg";

  const [twState, tween] = createTween({ x: 0 });
  const [tlState, timeline] = createTimeline({ x: 0, y: 0 });

  tween.to({ x: 150 }).easing(Easing.Circular.InOut).duration(1.5);

  timeline
    .to({ x: 250, duration: 2, easing: Easing.Quadratic.Out })
    .to({ y: 250, duration: 2, easing: Easing.Bounce.Out }, "-=1")
    .to({ x: 0, y: 0, duration: 1, easing: Easing.Back.InOut }, "+=1");

  console.log(tween, timeline);
</script>

<main>
  <div
    style:translate={`${tlState.x}px ${tlState.y}px`}
    style:display="inline-block"
  >
    <img
      src={viteLogo}
      class="logo"
      alt="Vite Logo"
      style:translate={`${twState.x}px`}
    />
    <img
      src={svelteLogo}
      class="logo svelte"
      alt="Svelte Logo"
      style:translate={`${-twState.x}px`}
    />
  </div>
  <h1>Svelte + Tween</h1>

  <div class="card">
    <h2>Tween</h2>
    <button
      onclick={() =>
        !tween.isPlaying &&
        (twState.x !== 150
          ? tween.to({ x: 150 }).startFromLast()
          : tween.to({ x: 0 }).startFromLast())
      }
    >
      Start
    </button>
    <button onclick={() => tween.pause()}>Pause</button>
    <button onclick={() => tween.reverse()}>Reverse</button>
    <button onclick={() => tween.stop()}>Stop</button>
  </div>
  <div class="card">
    <h2>Timeline</h2>
    <button onclick={() => timeline.play()}>Play</button>
    <button onclick={() => timeline.pause()}>Pause</button>
    <button onclick={() => timeline.reverse()}>Reverse</button>
    <button onclick={() => timeline.seek(0)}>Seek Start</button>
    <button onclick={() => timeline.seek(2)}>Seek 2s</button>
    <button onclick={() => timeline.stop()}>Stop</button>
  </div>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
</style>

// playground/vue/src/App.vue
<script setup lang="ts">
import { Easing } from "@thednp/tween";
import { useTween, useTimeline } from "@thednp/tween/vue";

const [twState, tween] = useTween({ x: 0 });
const [tlState, timeline] = useTimeline({ x: 0, y: 0 });

tween.to({ x: 150 }).easing(Easing.Circular.InOut).duration(1.5);

timeline
  .to({ x: 250, duration: 2, easing: Easing.Quadratic.Out })
  .to({ y: 250, duration: 2, easing: Easing.Bounce.Out }, "-=1")
  .to({ x: 0, y: 0, duration: 1, easing: Easing.Back.InOut }, "+=1");

console.log(tween, timeline);
</script>

<template>
  <div :style="{ translate: `${tlState.x}px ${tlState.y}px`, display: 'inline-block' }">
    <img src="/vite.svg" class="logo" alt="Vite logo" :style="{ translate: `${twState.x}px` }" />
    <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" :style="{ translate: `${-twState.x}px` }" />
  </div>
  <h1>Tween + Vue</h1>

  <div class="card">
    <h2>Tween</h2>

    <button type="button" @click="() => {
      tween
        .to({ x: twState.x === 150 ? 0 : 150 })
        .startFromLast();
    }">Start</button>
    <button type="button" @click="() => tween.pause()">Pause</button>
    <button type="button" @click="() => tween.reverse()">Reverse</button>
    <button type="button" @click="() => tween.stop()">Stop</button>
  </div>

  <div class="card">
    <h2>Timeline</h2>

    <button type="button" @click="() => timeline.play()">Play</button>
    <button type="button" @click="() => timeline.pause()">Pause</button>
    <button type="button" @click="() => timeline.seek(0)">Seek</button>
    <button type="button" @click="() => timeline.reverse()">Reverse</button>
    <button type="button" @click="() => timeline.stop()">Stop</button>
  </div>

  <div class="card">
    <p>
      Edit <code>App.vue</code> to test HMR
    </p>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

button+button {
  margin-left: 1rem
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
