// playground/vue/src/App.vue
<script setup lang="ts">
import { Easing } from "@thednp/tween";
import { useTween, useTimeline } from "@thednp/tween/vue";

const [twState, tween] = useTween({ x: 0 });
const [tlState, timeline] = useTimeline({ x: 0, y: 0 });

tween.to({ x: 150 }).easing(Easing.Circular.InOut).duration(1.5);

timeline
  .to({ x: 250, duration: 2, easing: Easing.Quadratic.Out })
  .to({ y: 250, duration: 2, easing: Easing.Bounce.Out }, "-=1")
  .to({ x: 0, y: 0, duration: 1, easing: Easing.Back.InOut }, "+=1");

console.log(tween, timeline);
</script>

<template>
  <div :style="{ translate: `${tlState.x}px ${tlState.y}px`, display: 'inline-block' }">
    <img src="/vite.svg" class="logo" alt="Vite logo" :style="{ translate: `${twState.x}px` }" />
    <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" :style="{ translate: `${-twState.x}px` }" />
  </div>
  <h1>Tween + Vue</h1>

  <div class="card">
    <h2>Tween</h2>

    <button type="button" @click="() => {
      tween
        .to({ x: twState.x === 150 ? 0 : 150 })
        .startFromLast();
    }">Start</button>
    <button type="button" @click="() => tween.pause()">Pause</button>
    <button type="button" @click="() => tween.reverse()">Reverse</button>
    <button type="button" @click="() => tween.stop()">Stop</button>
  </div>

  <div class="card">
    <h2>Timeline</h2>

    <button type="button" @click="() => timeline.play()">Play</button>
    <button type="button" @click="() => timeline.pause()">Pause</button>
    <button type="button" @click="() => timeline.seek(0)">Seek</button>
    <button type="button" @click="() => timeline.reverse()">Reverse</button>
    <button type="button" @click="() => timeline.stop()">Stop</button>
  </div>

  <div class="card">
    <p>
      Edit <code>App.vue</code> to test HMR
    </p>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

button+button {
  margin-left: 1rem
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// playground/preact/src/app.tsx
import { useEffect } from "preact/hooks";
import { useTween, useTimeline } from "@thednp/tween/preact";
import { Easing } from "@thednp/tween";
import preactLogo from "./assets/preact.svg";
import viteLogo from "/vite.svg";
import "./app.css";

export function App() {
  const [twState, tween] = useTween({ x: 0 });
  const [tlState, timeline] = useTimeline({ x: 0, y: 0 });

  useEffect(() => {
    tween
    .to({ x: 150 })
    .easing(Easing.Quadratic.InOut).duration(1.5);

    timeline
      .to({ x: 150, duration: 2, easing: Easing.Quadratic.Out })
      .to({ y: 150, duration: 2, easing: Easing.Bounce.Out }, "-=1")
      .to({ x: 0, y: 0, duration: 1, easing: Easing.Back.InOut }, "+=1");
  }, []);

  // test re-render
  // console.log({ tween, timeline });

  return (
    <>
      <div style={`translate: ${tlState.x}px ${tlState.y}px; display: inline-block`}>
        <img
          src={viteLogo}
          className="logo"
          alt="Vite logo"
          style={`translate: ${twState.x}px`}
        />
        <img
          src={preactLogo}
          className="logo preact"
          alt="Preact logo"
          style={`translate: ${-twState.x}px`}
        />
      </div>
      <h1>Preact + Tween</h1>
      <div class="card">
        <h2>Tween</h2>
        <button
          onClick={() =>
            !tween.isPlaying &&
            (twState.x !== 150
              ? tween.to({ x: 150 }).startFromLast()
              : tween.to({ x: 0 }).startFromLast())
          }
        >
          Start
        </button>
        <button onClick={() => tween.pause()}>Pause</button>
        <button onClick={() => tween.reverse()}>Reverse</button>
        <button onClick={() => tween.stop()}>Stop</button>
      </div>
      <div class="card">
        <h2>Timeline</h2>
        <button onClick={() => timeline.play()}>Play</button>
        <button onClick={() => timeline.pause()}>Pause</button>
        <button onClick={() => timeline.reverse()}>Reverse</button>
        <button onClick={() => timeline.seek(0)}>Seek Start</button>
        <button onClick={() => timeline.seek(2)}>Seek 2s</button>
        <button onClick={() => timeline.stop()}>Stop</button>
      </div>
    </>
  );
}
